# Site settings
title:          Simone Dutto
description:    "My blog"
url:            https://SimoneDutto.github.io
collections:
  projects:
  books:

# Author
author:
  name:         Simone Dutto

# Build settings
markdown:       kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  parse_block_html: true  # This ensures HTML blocks are processed
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
